name: wether_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  http: ^1.2.0
  geolocator: ^11.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  weather_icons: ^3.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/image/
